Repository hacs/default, pull requests merged in 2020-05, with the labels that each got.

#366 Adds new plugin [Sian-Lee-SA/honeycomb-menu]
  plugin
Labels: New default repository

#370 Adds new integration [rkoebrugge/hacs-youless-component]
  integration
Labels: New default repository

#367 Adds new integration [peternijssen/home-assistant-jumbo]
  integration
Labels: New default repository

#373 Adds new appdaemon [Mohlsson/ReplayLightsHistory]
  appdaemon
Labels: New default repository

#381 Adds new plugin [Voxxie/lovelace-jumbo-card]
  plugin
Labels: New default repository

#376 Adds new integration [Bouni/drkblutspende]
  integration
Labels: New default repository

#374 Adds new plugin [fineemb/lovelace-cn-map-card]
  plugin
Labels: New default repository

#364 Adds new appdaemon [UbhiTS/ad-alexasmarttalkingthermostat]
  appdaemon
Labels: New default repository

#383 Adds new integration [robbinjanssen/home-assistant-omnik-inverter]
  integration
Labels: New default repository

#397 Adds new plugin [r-renato/ha-card-weather-conditions]
  plugin
Labels: New default repository

#382 Adds new plugin [marksie1988/atomic-calendar-revive]
  plugin
Labels: New default repository

#385 Adds new integration [Bouni/luxtronik]
  integration
Labels: New default repository

#386 Adds new integration [freol35241/ltss]
  integration
Labels: New default repository

#388 Adds new integration [Cyr-ius/hass-hue-service-advanced]
  integration
Labels: New default repository

#390 Adds new integration [gcorgnet/sensor.emby_upcoming_media]
  integration
Labels: New default repository

#391 Adds new plugin [fineemb/lovelace-air-filter-card]
  plugin
Labels: New default repository

#394 Adds new integration [msp1974/homeassistant-jlrincontrol]
  integration
Labels: New default repository

#398 Adds new integration [eyalcha/thermal]
  integration
Labels: New default repository

#399 Adds new plugin [denysdovhan/vacuum-card]
  plugin
Labels: New default repository

#400 Adds new plugin [Imbuzi/meteo-france-weather-card]
  plugin
Labels: New default repository

#404 Adds new integration [nagyrobi/home-assistant-custom-components-cover-rf-time-based]
  integration
Labels: New default repository

#407 Adds new integration [youdroid/home-assistant-couchpotato]
  integration
Labels: New default repository

#410 Adds new plugin [GeorgeSG/lovelace-time-picker-card]
  plugin
Labels: New default repository

#412 Adds new integration [cagnulein/switchbot_press]
  integration
Labels: New default repository

#413 Adds new integration [pfunkmallone/HACS-camect-integration]
  integration
Labels: New default repository

#417 Adds new appdaemon [Petro31/ad_count_entities]
  appdaemon
Labels: New default repository, Not finished

#418 Adds new plugin [clayauld/lovelace-darksky-card]
  plugin
Labels: New default repository

#419 Adds new integration [youdroid/home-assistant-sickchill]
  integration
Labels: New default repository

#420 Adds new integration [garbled1/balboa_homeassistan]
  integration
Labels: New default repository

#421 Adds new integration [garbled1/homeassistant_ecowitt]
  integration
Labels: New default repository

#423 Adds new theme [DickSwart/swart_ninja_dark_theme]
  theme
Labels: New default repository

#424 Adds new plugin [pfunkmallone/HACS-camect-custom_card]
  plugin
Labels: New default repository

#426 Adds new theme [kibibit/hass-kibibit-theme]
  theme
Labels: New default repository

#429 Adds new integration [eseglem/hass-wattbox]
  integration
Labels: New default repository

#431 Adds new integration [briis/meteobridge]
  integration
Labels: New default repository

#432 Adds new integration [nikrolls/homeassistant-goldair-climate]
  integration
Labels: New default repository

#433 Adds new integration [briis/weatherbit]
  integration
Labels: New default repository

#434 Adds new integration [eyalcha/read_your_meter]
  integration
Labels: New default repository

#441 Adds new plugin [dimagoltsman/generic-remote-control-card]
  plugin
Labels: New default repository

#438 Adds new integration [sockless-coding/panasonic_cc]
  integration
Labels: New default repository

#416 Adds new plugin [madmicio/LG-WebOS-Remote-Control]
  plugin
Labels: New default repository

#444 Adds new integration [jeroenterheerdt/HAsmartirrigation]
  integration
Labels: New default repository

#446 Adds new integration [sockless-coding/garo_wallbox]
  integration
Labels: New default repository

#447 Adds new integration [youdroid/home-assistant-gitea]
  integration
Labels: New default repository

#450 Adds new appdaemon [simonhq/accu_allergies]
  appdaemon
Labels: New default repository

#466 Adds new integration [nitobuendia/oura-custom-component]
  integration
Labels: New default repository

#457 Adds new integration [Pyhive/HA-Hive-Custom-Component]
  integration
Labels: New default repository

#452 Adds new integration [heyajohnny/cryptoinfo]
  integration
Labels: New default repository

#453 Adds new integration [GeorgeSG/ha-slack-user]
  integration
Labels: New default repository

#454 Adds new plugin [jeremywillans/lovelace-roomba-vacuum-card]
  plugin
Labels: New default repository, Not finished

#458 Adds new plugin [dimagoltsman/refreshable-picture-card]
  plugin
Labels: New default repository

#461 Adds new integration [vlumikero/home-assistant-securitas]
  integration
Labels: New default repository

#467 Adds new integration [vanstinator/hass-raincloud]
  integration
Labels: New default repository

#470 Adds new appdaemon [simonhq/snowydams]
  appdaemon
Labels: New default repository

#471 Adds new integration [laszlojakab/homeassistant-dijnet]
  integration
Labels: New default repository

#474 Adds new appdaemon [crserran/home-alarm]
  appdaemon
Labels: New default repository

#476 Adds new integration [mac-zhou/midea-ac-py]
  integration
Labels: New default repository

#480 Adds new integration [laszlojakab/homeassistant-easycontrols]
  integration
Labels: New default repository

#472 Adds new integration [DSorlov/hasl-platform]
  integration
Labels: New default repository

#486 New trigger
  .github/workflows/check-archived.yml
  .github/workflows/check-brands.yml
  .github/workflows/check-fork.yml
  .github/workflows/check-hacs-manifest.yml
  .github/workflows/check-hacs.yaml
  .github/workflows/check-hassfest.yml
  .github/workflows/check-images.yml
  .github/workflows/check-info.yml
  .github/workflows/check-manifest.yml
  .github/workflows/check-owner.yml
  .github/workflows/check-repository.yml
  .github/workflows/check-wheels.yml
  .github/workflows/lint-jq.yml
Labels: Not finished

#488 Merge CI files
  .github/workflows/check-archived.yml
  .github/workflows/check-brands.yml
  .github/workflows/check-fork.yml
  .github/workflows/check-hacs-manifest.yml
  .github/workflows/check-hacs.yaml
  .github/workflows/check-hassfest.yml
  .github/workflows/check-images.yml
  .github/workflows/check-info.yml
  .github/workflows/check-manifest.yml
  .github/workflows/check-owner.yml
  .github/workflows/check-repository.yml
  .github/workflows/check-wheels.yml
  .github/workflows/checks.yml
  .github/workflows/lint-jq.yml
  .github/workflows/lint-sorted.yml
  .github/workflows/lint.yml
Labels: Not finished

#482 changed github account name
  appdaemon
  integration
Labels: Not finished

#484 Adds new integration [dynasticorpheus/gigasetelements-ha]
  integration
Labels: New default repository

#487 Adds new integration [gadgetchnnel/entities_calendar]
  integration
Labels: New default repository

#456 Adds new plugin [madmicio/channel-pad]
  plugin
Labels: New default repository

#479 Adds new appdaemon [simonhq/act_garbage]
  appdaemon
Labels: New default repository

#462 Adds new integration [tellerbop/havistapool]
  integration
Labels: New default repository

#491 Adds new plugin [Villhellm/custom-sidebar]
  plugin
Labels: New default repository

#492 Adds new appdaemon [hechi/GoodnightT]
  appdaemon
Labels: New default repository

#493 Adds new plugin [iswitch/ha-yandex-icons]
  plugin
Labels: New default repository
